ymlfile=src/test/resources/openapi.yaml
base_uri_1=https://gorest.co.in/public/v2/
base_path_1=users
access_token=37e722e200d2b1c65596bc9295780b6edb58bf2ad2c82341a5cb6b7f4b89fdfc
base_path_2=users/5770
dummy_base_uri=https://dummyjson.com/
dummy_base_path =products/1